---
debug: true
contextTimeout: 5

server:
  address: ":8080"

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  database: test
  username: "root"
  password: "root"
  maxIdleConns: 20
  maxLeftTime: 40
  name: "db_test"

log:
  fileName: test_log.log
  logLevel: 1
  maxSizeMB: 20
  maxBackupCount: 200
  maxKeepDays: 7